### ISSUE TITLE
Tracer not working in logger with Kotlin coroutine

### ISSUE THREAD

**Issue by gismoranas** [zalando/opentracing-toolbox#327]
I'm using the default spring configuration and if I do this:

`GlobalScope.launch{ someOperationThatUsuallyLogsWithTracer() }`

I don't see the tracer in the logs. 

Maybe I'm missing something in the settings?

Not sure if this is a bug or a feature request. Please feel free to ask for details in order to reproduce it.

**Comment by whiskeysierra** [comment]
Tracer is built on top of OpenTracing's concept of *active spans* which, implementation-wise, are built on top of `ThreadLocal`. My understanding of Kotlin's coroutines is limited, but I believe anything around ThreadLocal won't work because it's not necessarily the same thread executing it.

This is for Brave, but discusses the issue https://github.com/openzipkin/brave/issues/820

**Comment by whiskeysierra** [comment]
I'll close this for the time being. If you have some more information/requests/etc., then feel free to reopen this.
